maestro_admin_menu:
    this_is_empty_menu:
        uri: "#test"
        order: 2
        children:
            post_menu_2:
                route: "admin_homepage"
                routeParameters:
                    id: 52
                label: Post List 2
                order: 2
            post_menu:
                uri: "@post_list"
                label: Post List
    this_is_empty_menu_2:
        uri: "#test"
        label: This is the label 2
        order: 1
        children:
            post_menu_bis:
                uri: "@post_list"
                label: Post List