parameters:
    maestro.menu.builder.class: Maestro\Bundle\NavigationBundle\Menu\MenuBuilder

services:
    maestro.menu.builder:
        class: %maestro.menu.builder.class%
        arguments: 
            - "@knp_menu.factory"
            - "@event_dispatcher"