parameters:
    maestro.menu.configuration_loader.class: Maestro\Bundle\NavigationBundle\Menu\ConfigurationLoader

services:
    maestro.menu.configuration_loader:
        class: %maestro.menu.configuration_loader.class%
    
    maestro.menu.builder:
        class: Maestro\Bundle\NavigationBundle\Menu\MenuBuilder
        arguments: 
            - "@knp_menu.factory"

    maestro.menu.admin:
        class: Knp\Menu\MenuItem
        factory_service: maestro.menu.builder
        factory_method: createMenu
        arguments: 
          - "@request"
          - "admin"
        scope: request
        tags:
            - { name: knp_menu.menu, alias: admin }