parameters:
    jb_config.menu.builder.class: Jb\Bundle\ConfigKnpMenuBundle\Menu\MenuBuilder

services:
    jb_config.menu.builder:
        class: %jb_config.menu.builder.class%
        arguments:
            - "@knp_menu.factory"
            - "@event_dispatcher"