language: php

sudo: false

php:
  - 5.6
  - 7.0

before_script:
  - phpenv config-add travis.php.ini
  - composer install -n

script:
  - vendor/bin/phpunit -c Tests/
  - vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=vendor .
